# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    conserto.twig_extension:
          class: CONSERTO\KiosqueBundle\Twig\ConsertoExtension
          tags:
            - { name : twig.extension }

    Symfony\Component\Ldap\LdapClient:
        arguments:
            - 192.168.1.2
            - 389
            - 3
            - false
            - false
