<?php

namespace CONSERTO\KiosqueBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{

  public function getmagazineId($string,$category, $page, $nbelementparpage, $sorts)
  {
    $search= '';
    $tab = explode(" ",$string);
    foreach ($tab as $key) {
      $key = "%".$key."%";
      $search = $search.$key." OR LIKE ";
      $search = substr($search, 0, -9);
    }
      if ($sorts == 'date'){
          $paramSearch = "desc";
      }else{
          $paramSearch = "asc";
      }

    $qb = $this->createQueryBuilder('c');


    $qb
     ->join('c.magazines', 'm')
     ->addSelect('m');

     if ($category != '') {
       $qb
       ->where('c.name LIKE :category')
       ->setParameter('category', $category);
     }


    $qb
      ->select('m.id')
      ->andWhere('m.title LIKE :string OR m.content LIKE :string')
      ->setParameter('string', $search);

    $qb->orderBy("m.$sorts",$paramSearch);

    // Enfin, on retourne le résultat
     return $qb
      ->getQuery()
      ->setMaxResults($nbelementparpage)
      ->setFirstResult(0+$page*$nbelementparpage)
      ->getResult()
    ;
  }

  public function getNbDocInListeWithCategoriesAndSearch($string, $category)
  {
    $search= '';
    $tab = explode(" ",$string);
    foreach ($tab as $key) {
      $key = "%".$key."%";
      $search = $search.$key." OR LIKE ";
      $search = substr($search, 0, -9);
    }

    $qb = $this->createQueryBuilder('c');


    $qb
     ->join('c.magazines', 'm')
     ->addSelect('m')
     ->where('c.name = :category')
   ;

    return $qb
      ->select('COUNT(m)')
      ->where('c.name LIKE :category')
      ->andWhere('m.title LIKE :string OR m.content LIKE :string')
      ->setParameter('string', $search)
      ->setParameter('category', $category)
      ->getQuery()
      ->getSingleScalarResult();
  }

  public function getNbDocInListe()
  {
    return $this->createQueryBuilder('m')
      ->select('COUNT(m)')
      ->getQuery()
      ->getSingleScalarResult();
  }

}
